"use client";

import { useEffect, useState } from "react";

type Product = { name: string; price: string; quantity: string; maxQuantity: string; description: string; unit: string };
type Tier = { minQuantity: string; maxQuantity: string; unitPrice: string };
type PriceGroup = { name: string; productIndexes: number[]; tiers: Tier[] };
type Group = { id: string; name: string; end_at: string };

const blankProduct = (): Product => ({ name: "", price: "", quantity: "", maxQuantity: "", description: "", unit: "個" });

export default function CopyGroupPage() {
  const [groups, setGroups] = useState<Group[]>([]); const [sourceId, setSourceId] = useState(""); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [startAt, setStartAt] = useState(""); const [endAt, setEndAt] = useState(""); const [products, setProducts] = useState<Product[]>([]); const [priceGroups, setPriceGroups] = useState<PriceGroup[]>([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");

  useEffect(() => { fetch("/api/group-buys", { cache: "no-store" }).then((r) => r.json()).then((r) => setGroups(r.data ?? [])).catch(() => setError("無法讀取團購清單")); }, []);
  async function selectGroup(id: string) { setSourceId(id); if (!id) return; setLoading(true); setError(""); setMessage(""); try { const response = await fetch(`/api/group-buys/${id}`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "無法取得團購資料"); const data = result.data; setName(`${data.name}（複製）`); setDescription(data.description ?? ""); setStartAt(""); setEndAt(""); setProducts((data.products ?? []).map((p: any) => ({ name: p.name ?? "", price: String(p.price ?? ""), quantity: String(p.quantity ?? ""), maxQuantity: p.max_quantity == null ? "" : String(p.max_quantity), description: p.description ?? "", unit: p.unit ?? "個" }))); setPriceGroups((data.priceGroups ?? []).map((g: any) => ({ name: g.name ?? "價格群組", productIndexes: [...(g.productIndexes ?? [])], tiers: (g.tiers ?? []).map((t: any) => ({ minQuantity: String(t.minQuantity ?? 1), maxQuantity: t.maxQuantity == null ? "" : String(t.maxQuantity), unitPrice: String(t.unitPrice ?? "") })) }))); } catch (e) { setError(e instanceof Error ? e.message : "複製失敗"); } finally { setLoading(false); } }
  function updateProduct(i: number, patch: Partial<Product>) { setProducts((xs) => xs.map((x, j) => j === i ? { ...x, ...patch } : x)); }
  function addProduct() { setProducts((xs) => [...xs, blankProduct()]); }
  function removeProduct(i: number) { if (products.length === 1) return; setProducts((xs) => xs.filter((_, j) => j !== i)); setPriceGroups((gs) => gs.map((g) => ({ ...g, productIndexes: g.productIndexes.filter((x) => x !== i).map((x) => x > i ? x - 1 : x) }))); }
  async function submit() { setError(""); setMessage(""); if (!name.trim() || !startAt || !endAt) { setError("請填寫團購名稱、開始時間與結束時間"); return; } if (new Date(endAt) <= new Date(startAt)) { setError("結束時間必須晚於開始時間"); return; } const valid = products.filter((p) => p.name.trim()); if (!valid.length) { setError("至少保留一個商品"); return; } const indexMap = new Map<number, number>(); products.forEach((p, i) => { if (p.name.trim()) indexMap.set(i, indexMap.size); }); const payloadProducts = products.filter((p) => p.name.trim()).map((p) => ({ ...p, price: p.price || "0", quantity: p.quantity || "0" })); const payloadGroups = priceGroups.map((g) => ({ name: g.name, productIndexes: g.productIndexes.map((i) => indexMap.get(i) ?? -1).filter((i) => i >= 0), tiers: g.tiers })).filter((g) => g.productIndexes.length); if (!payloadGroups.length) { setError("複製的團購沒有有效的價格群組"); return; } setSaving(true); try { const response = await fetch("/api/group-buys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, startAt, endAt, products: payloadProducts, priceGroups: payloadGroups }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "建立失敗"); setMessage("新團購建立成功，可以回到新建團購頁面繼續建立其他團購。"); } catch (e) { setError(e instanceof Error ? e.message : "建立團購失敗"); } finally { setSaving(false); } }

  return <main className="min-h-screen px-5 py-6 md:ml-64 md:px-8"><div className="mx-auto max-w-6xl"><section className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-xs font-medium text-[var(--accent)]">Admin</p><h1 className="mt-1 text-xl font-bold">複製既有團購建立新團購</h1><p className="mt-1 text-xs text-[var(--muted)]">選一個過去的團購帶入資料。之後只需要刪除不要的商品或新增新品項，不必重新輸入全部內容。</p><div className="mt-4 grid gap-2 md:grid-cols-3"><div className="md:col-span-3"><label className="text-xs font-medium">複製來源</label><select value={sourceId} onChange={(e) => selectGroup(e.target.value)} disabled={loading} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm"><option value="">請選擇既有團購</option>{groups.map((g) => <option key={g.id} value={g.id}>{g.name}（結束：{new Date(g.end_at).toLocaleDateString("zh-TW")}）</option>)}</select></div><div className="md:col-span-3"><label className="text-xs font-medium">開團名稱</label><input value={name} onChange={(e) => setName(e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /></div><div><label className="text-xs font-medium">開始時間</label><input type="datetime-local" value={startAt} onChange={(e) => setStartAt(e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /></div><div><label className="text-xs font-medium">結束時間</label><input type="datetime-local" value={endAt} onChange={(e) => setEndAt(e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /></div><div><label className="text-xs font-medium">說明</label><input value={description} onChange={(e) => setDescription(e.target.value)} className="mt-1 w-full rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /></div></div></section>

    {!!products.length && <section className="mt-4 space-y-3"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">複製的商品</h2><p className="mt-0.5 text-xs text-[var(--muted)]">保留的商品會直接沿用原本資料。需要時直接刪除或新增。</p></div><button type="button" onClick={addProduct} className="rounded-lg bg-[var(--accent)] px-3 py-1.5 text-xs font-semibold text-white">＋ 新增商品</button></div>{products.map((p, i) => <div key={i} className="rounded-2xl bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h3 className="text-sm font-bold">商品 {i + 1}</h3><button type="button" onClick={() => removeProduct(i)} disabled={products.length === 1} className="rounded-lg border border-red-200 px-3 py-1.5 text-xs text-red-600 disabled:opacity-40">刪除商品</button></div><div className="mt-3 grid gap-2 md:grid-cols-4"><input value={p.name} onChange={(e) => updateProduct(i, { name: e.target.value })} placeholder="品名" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm md:col-span-2" /><input type="number" value={p.price} onChange={(e) => updateProduct(i, { price: e.target.value })} placeholder="價格" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /><input type="number" value={p.quantity} onChange={(e) => updateProduct(i, { quantity: e.target.value })} placeholder="數量" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /><input value={p.unit} onChange={(e) => updateProduct(i, { unit: e.target.value })} placeholder="單位" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /><input type="number" value={p.maxQuantity} onChange={(e) => updateProduct(i, { maxQuantity: e.target.value })} placeholder="最高購買數量" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm" /><input value={p.description} onChange={(e) => updateProduct(i, { description: e.target.value })} placeholder="商品說明" className="rounded-lg border border-[var(--border)] px-3 py-2 text-sm md:col-span-3" /></div></div>)}</section>}

    {!!priceGroups.length && <section className="mt-4 rounded-2xl bg-white p-4 shadow-sm"><h2 className="text-lg font-bold">原團購價格階梯</h2><p className="mt-1 text-xs text-[var(--muted)]">價格階梯會跟著複製。刪除商品後，系統會自動移除該商品在價格群組中的關聯。</p><div className="mt-3 space-y-2">{priceGroups.map((g, i) => <div key={i} className="rounded-xl bg-[#f4f5f1] p-3"><p className="text-sm font-semibold">{g.name}</p><p className="mt-1 text-xs text-[var(--muted)]">商品：{g.productIndexes.map((x) => products[x]?.name).filter(Boolean).join("、") || "無"}</p><div className="mt-2 flex flex-wrap gap-2">{g.tiers.map((t, j) => <span key={j} className="rounded-lg bg-white px-2 py-1 text-xs">{t.minQuantity}～{t.maxQuantity || "以上"}：${t.unitPrice}</span>)}</div></div>)}</div></section>}

    {error && <div className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}{message && <div className="mt-4 rounded-xl bg-[#edf7f3] px-4 py-3 text-sm text-[var(--accent)]">{message}</div>}
    <div className="mt-4 flex gap-2"><a href="/admin" className="flex-1 rounded-xl border border-[var(--border)] px-4 py-3 text-center text-sm">回新建團購</a><button type="button" onClick={submit} disabled={saving || !products.length} className="flex-1 rounded-xl bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving ? "建立中..." : "建立新團購"}</button></div>
  </div></main>;
}
